### ISSUE TITLE
Unable to process file with % character in header

### ISSUE THREAD

**Issue by mill1000** [jwuavionix/CSVTOKMLConverter#4]
The input log files now contain a Battery Remaining % field. The tool rejects these files as having an invalid headers.

**Comment by adamgoldsmith640** [comment]
Just now seeing this. Would it be acceptable for my code to simply remove the %? If not, please advise on how you would like it handled.

**Comment by jwuavionix** [comment]
I don't understand why the % needs to be stripped, it's a valid ascii char and isn't part of the CSV formatting so it shouldn't have a problem parsing them.

**Comment by adamgoldsmith640** [comment]
I can't say I do either, but the XmlWriter class is what's throwing the error that says that. I've taken it to mean that well-formed XML tags can't have the % char in them, and therefore, presumably neither can KML. Would you like me to research that, and confirm or deny the notion if I can?

I did a quick search and found something about CDATA, but I'm not sure it'll end up being useful, It mostly seems to allow otherwise-prohibited symbols in the data, not so much for the tags. I may be mistaken, but that's my impression.

Either way, the best I'd hope for from that route would be something like 
<![CDATA[BatteryRemaining%]]>99</![CDATA[BatteryRemaining%]]>
Would such a result be useful?

**Comment by jwuavionix** [comment]
A quick google search shows that it's an invalid character for a XML tag.
So you should modify the code to strip any invalid characters from the tag
names to allow the KML file to be created.  Looks like .NET even gives you
a function to validate the name.
https://msdn.microsoft.com/en-us/library/system.xml.xmlconvert.verifyname.aspx
I'm sure there's plenty of other resources out there to help validate the
name and strip any invalid characters.

**Comment by adamgoldsmith640** [comment]
Having followed what you said, quite some time ago now, I thought the problem remained. I decided to work on the other issue for a while, but by the time I thought about this again, maybe a week later, I realized it had stopped happening.

Seeing as it's been a month now, and I've still not seen it pop back up, I think I'll close this issue finally. I think I must have neglected to test the very last thing I did, whatever that was, and figured it was still broken.
